import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MyWebsite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>welcome to wonderl`s website</h2>
      <div className="">
        <h3>功能区</h3>
      </div>

      <div className="">
        <h3>记录区</h3>
      </div>
    </div>
  );
};

export default Home;
